l_joint_1: 0.0
l_joint_2: 0.0
l_joint_3: 0.0
l_joint_4: 0.0
l_joint_5: 0.0
l_joint_6: 0.0
l_joint_7: 0.0
r_joint_1: 0.0
r_joint_2: 0.0
r_joint_3: 0.0
r_joint_4: 0.0
r_joint_5: 0.0
r_joint_6: 0.0
r_joint_7: 0.0
