controller_list:
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - r_joint_1
      - r_joint_2
      - r_joint_3
      - r_joint_4
      - r_joint_5
      - r_joint_6
      - r_joint_7
      - r_tool_joint
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - l_joint_1
      - l_joint_2
      - l_joint_3
      - l_joint_4
      - l_joint_5
      - l_joint_6
      - l_joint_7
      - l_tool_joint
initial:  # Define initial robot poses per group
  - group: right_arm
    pose: right_home