controller_list:
  - name: fake_ur5e_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
initial:  # Define initial robot poses per group
  - group: ur5e
    pose: home