left_panda_joint1: 0.0
left_panda_joint2: 0.0
left_panda_joint3: 0.0
left_panda_joint4: -1.5707
left_panda_joint5: 0.0
left_panda_joint6: 1.5707
left_panda_joint7: 0.0
right_panda_joint1: 0.0
right_panda_joint2: 0.0
right_panda_joint3: 0.0
right_panda_joint4: -1.5707
right_panda_joint5: 0.0
right_panda_joint6: 1.5707
right_panda_joint7: 0.0
