controller_list:
  - name: fake_r_timda_single7_controller
    type: $(arg fake_execution_type)
    joints:
      - r_joint_1
      - r_joint_2
      - r_joint_3
      - r_joint_4
      - r_joint_5
      - r_joint_6
  - name: fake_l_timda_single7_controller
    type: $(arg fake_execution_type)
    joints:
      - l_joint_1
      - l_joint_2
      - l_joint_3
      - l_joint_4
      - l_joint_5
      - l_joint_6
initial:  # Define initial robot poses per group
  - group: r_timda_single7
    pose: right_home
  - group: l_timda_single7
    pose: left_home