controller_list:
  - name: fake_iiwa7_controller
    type: $(arg fake_execution_type)
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
initial:  # Define initial robot poses per group
  - group: iiwa7
    pose: take_pic